/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/restaurant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RestaurantController_createMyRestaurant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/restaurant/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RestaurantController_getMyRestaurant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["RestaurantController_updateMyRestaurant"];
        trace?: never;
    };
    "/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SubscriptionController_getSubscription"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CustomerController_getRestaurantCustomers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rewards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RewardController_getRestaurantRewards"];
        put?: never;
        post: operations["RewardController_createReward"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rewards/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["RewardController_updateReward"];
        trace?: never;
    };
    "/rewards/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["RewardController_archiveReward"];
        trace?: never;
    };
    "/rewards/{id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["RewardController_draftReward"];
        trace?: never;
    };
    "/rewards/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["RewardController_publishReward"];
        trace?: never;
    };
    "/promotions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PromotionController_getRestaurantPromotions"];
        put?: never;
        post: operations["PromotionController_createPromotion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/promotions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["PromotionController_updatePromotion"];
        trace?: never;
    };
    "/promotions/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["PromotionController_archivePromotion"];
        trace?: never;
    };
    "/promotions/{id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["PromotionController_draftPromotion"];
        trace?: never;
    };
    "/promotions/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["PromotionController_publishPromotion"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserDto: {
            id: string;
            email: string;
            name: string;
            emailVerified: boolean;
            image?: string;
            firstName: string;
            lastName?: string;
            /** Format: date-time */
            dateOfBirth?: string;
            /** @enum {string} */
            gender?: "male" | "female";
            city?: string;
            country?: string;
            /** @enum {string} */
            language: "fr" | "en" | "es";
            linkCode: string;
            isActive: boolean;
            isRestaurantOwner: boolean;
            stripeCustomerId?: string;
        };
        CreateRestaurantDto: {
            name: string;
            latitude: number;
            longitude: number;
            /** @enum {string} */
            plan: "starter" | "growth" | "pro";
        };
        MediaDto: {
            id: string;
            mimeType?: string;
            size?: number;
            url: string;
        };
        RestaurantDto: {
            id: string;
            name: string;
            latitude?: number;
            longitude?: number;
            country?: string;
            city?: string;
            formattedAddress?: string;
            placeId?: string;
            googleMyBusinessLink?: string;
            averageRating: number;
            reviewCount: number;
            isActive: boolean;
            cloudwaitressId?: string;
            cloudwaitressUrl?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            medias: components["schemas"]["MediaDto"][];
        };
        UpdateRestaurantDto: {
            name?: string;
            latitude?: number;
            longitude?: number;
            mediaIds?: string[];
        };
        SubscriptionDto: {
            id: string;
            stripeSubscriptionId?: string;
            /** @enum {string} */
            plan: "starter" | "growth" | "pro";
            /** @enum {string} */
            status: "active" | "trialing" | "past_due" | "unpaid" | "incomplete" | "incomplete_expired" | "canceled" | "paused";
            cancelAtPeriodEnd: boolean;
            /** Format: date-time */
            currentPeriodEnd?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CustomerDto: {
            id: string;
            points: number;
            totalPointsGained: number;
            canSubmitRating: boolean;
            isInactive: boolean;
            /** Format: date-time */
            lastVisitDate?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            user: components["schemas"]["UserDto"];
        };
        PaginatedCustomersDto: {
            items: components["schemas"]["CustomerDto"][];
            total: number;
            page: number;
            limit: number;
        };
        RewardDto: {
            id: string;
            name: string;
            description?: string;
            pointRequired: number;
            /** @enum {string} */
            status: "active" | "draft" | "archived";
            usedCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            medias: components["schemas"]["MediaDto"][];
        };
        CreateRewardDto: {
            /** @enum {string} */
            status?: "active" | "draft";
            name: string;
            description?: string;
            pointRequired: number;
            mediaIds?: string[];
        };
        UpdateRewardDto: {
            name?: string;
            description?: string;
            pointRequired?: number;
            mediaIds?: string[];
        };
        PromotionDto: {
            targetedCustomers: components["schemas"]["CustomerDto"][];
            id: string;
            name: string;
            /** @enum {string} */
            audience: "all" | "inactive" | "targeted";
            /** @enum {string} */
            status: "active" | "upcoming" | "expired" | "draft" | "archived";
            /** Format: date-time */
            scheduledAt: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            usedCount: number;
            targetCount: number;
        };
        CreatePromotionDto: {
            name: string;
            /** @enum {string} */
            audience: "all" | "inactive" | "targeted";
            scheduledAt?: string;
            expiresAt?: string;
            customerIds?: string[];
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "draft" | "archived";
        };
        UpdatePromotionDto: {
            name?: string;
            /** @enum {string} */
            audience?: "all" | "inactive" | "targeted";
            /** Format: date-time */
            scheduledAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            customerIds?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    UserController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    RestaurantController_createMyRestaurant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRestaurantDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestaurantDto"];
                };
            };
        };
    };
    RestaurantController_getMyRestaurant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestaurantDto"];
                };
            };
        };
    };
    RestaurantController_updateMyRestaurant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRestaurantDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestaurantDto"];
                };
            };
        };
    };
    SubscriptionController_getSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionDto"];
                };
            };
        };
    };
    CustomerController_getRestaurantCustomers: {
        parameters: {
            query?: {
                search?: string;
                sortBy?: "latest" | "top";
                onlyInactive?: boolean;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCustomersDto"];
                };
            };
        };
    };
    RewardController_getRestaurantRewards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RewardDto"][];
                };
            };
        };
    };
    RewardController_createReward: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRewardDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RewardDto"];
                };
            };
        };
    };
    RewardController_updateReward: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRewardDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RewardDto"];
                };
            };
        };
    };
    RewardController_archiveReward: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RewardDto"];
                };
            };
        };
    };
    RewardController_draftReward: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RewardDto"];
                };
            };
        };
    };
    RewardController_publishReward: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RewardDto"];
                };
            };
        };
    };
    PromotionController_getRestaurantPromotions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromotionDto"][];
                };
            };
        };
    };
    PromotionController_createPromotion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePromotionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromotionDto"];
                };
            };
        };
    };
    PromotionController_updatePromotion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePromotionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromotionDto"];
                };
            };
        };
    };
    PromotionController_archivePromotion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromotionDto"];
                };
            };
        };
    };
    PromotionController_draftPromotion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromotionDto"];
                };
            };
        };
    };
    PromotionController_publishPromotion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromotionDto"];
                };
            };
        };
    };
}
